"""empty message

Revision ID: 7f251bd0d8b5
Revises: e2e091996f1f
Create Date: 2025-11-27 14:50:32.477152

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f251bd0d8b5"
down_revision = "e2e091996f1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("property_type", sa.String(), nullable=False))
        batch_op.create_index(batch_op.f("ix_entry_property_type"), ["property_type"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entry_property_type"))
        batch_op.drop_column("property_type")

    # ### end Alembic commands ###
