# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["latest"]
  pull_request:
    branches: ["latest"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CONTACT_EMAIL: test@example.com
      CONTACT_PHONE: 0123456789
      DEPARTMENT_NAME: 'HM Land Registry'
      DEPARTMENT_URL: https://www.gov.uk/government/organisations/land-registry
      POSTGRES_DB: db
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${{ secrets.PG_PASS }}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${{ secrets.PG_USER }}
      REDIS_HOST: cache
      REDIS_PORT: 6379
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SERVICE_NAME: 'Student exercise'
      SERVICE_PHASE: Beta
      SERVICE_URL: http://localhost
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
      - name: Check dependencies for known security vulnerabilities
        run: pip-audit -r requirements.txt
      - name: Check code for potential security vulnerabilities
        run: bandit -r . -x /tests
      #- name: Static type checking
      #  run: mypy . --install-types --non-interactive
      - name: Check code formatting
        run: |
          black . -t py314 -l 120 --check
          isort . -c
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - name: Unit tests with pytest
        run: python -m pytest tests/unit_tests/ --cov=app --cov-report=term-missing --cov-branch
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Run Docker Compose
        run: docker compose up -d
      - name: Acceptance tests with pytest
        run: python -m pytest tests/acceptance_tests/